### ISSUE TITLE
Incorrect Website Links

### ISSUE THREAD

**Issue by chrisbarnes2000** [hygames-team/gamebox#2]
See the photos below, the links need to be updated for this repo.
<img width="1680" alt="Screen Shot 2021-06-20 at 3 35 16 AM" src="https://user-images.githubusercontent.com/25515082/122670827-c5381600-d178-11eb-98f4-0af45f5c6eb6.png">
<img width="1680" alt="Screen Shot 2021-06-20 at 3 38 09 AM" src="https://user-images.githubusercontent.com/25515082/122670899-206a0880-d179-11eb-9572-9ae1f516dbec.png">

**Comment by NiklasEi** [comment]
Thanks for the reminder!
I updated the links.
